# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/gnn_processed/1GeV_pt_cut_quickstart_example

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [300, 20, 20] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
ptcut: 1.0
n_hits: 5
weight_leak: 1.0
weight_min: 0.
pt_interval: 0.5
checkpointing: True
use_pretrain: False
primary: False
noise: True
hard_ptcut: 0
edge_dropping_ratio: 0.
score_cut: 0.7

# Model parameters
model: BC-HGNN-GMM
spatial_channels: 3
cell_channels: 8
latent: 256
hidden: ratio
hidden_ratio: 2
emb_dim: 8
n_interaction_graph_iters: 6
n_hierarchical_graph_iters: 6
nb_node_layer: 3
nb_edge_layer: 2
output_layers: 3
knn: 100
train_r: 1.0
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 100
lr: 0.001
factor: 0.99
share_weight: False
patience: 1
regime: []
max_epochs: 500
majority_cut: 0.5
log_weight_ratio: 0
bipartitegraph_sparsity: 5
supergraph_sparsity: 10
min_cluster_size: 3
cluster_granularity: 3
emb_epoch: 50


# Toy Model
use_toy: False
num_tracks: 200
track_dis_width: 10
num_layers: 10
min_r: 1
max_r: 5
detector_width: 2
toy_eff: 0.9
toy_pur: 0.5