# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/embedding_processed/0GeV_cut_testing_high_eff/
output_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/filter_processed/0GeV_cut_testing_high_eff/
project: ITk_1GeV_Filter
edge_cut: 0.5

# Dataset parameters
pt_min: 0
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [100, 100, 100] # Number of [training, validation, testing] examples
endcaps: True
layerwise: False
layerless: True
noise: False
adjacent: False

# Model parameters
in_channels: 12
edges_per_batch: 10000
spatial_channels: 3
cell_channels: 9
hidden: 1024
nb_layer: 8
emb_channels: 0
layernorm: True
batchnorm: False
n_chunks: 12
ratio: 2
weight: 2
warmup: 50
lr: 0.01
factor: 0.3
patience: 2
regime: [ci]
max_epochs: 100

# Post-processing
callbacks: [] #[FilterInferenceCallback]

# Logging
wandb_save_dir: /global/cscratch1/sd/danieltm/ExaTrkX/wandb_data