# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/trackml-codalab/feature_store/

# Dataset parameters
datatype_names: [all_data] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [1000, 200, 1000] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
score_cut: 0.15
ptcut: 1.0
n_hits: 5
weight_leak: 0.5
weight_min: 0.
pt_interval: 0.5
checkpointing: True
use_pretrain: False
noise: False
hard_pt_cut: 0.5
noise_cut: 0.7

# Model parameters
spatial_channels: 3
cell_channels: 8
latent: 64
hidden: 64
mlp_hidden: 512
emb_dim: 8
n_interaction_graph_iters: 8
n_hierarchical_graph_iters: 10
pyramid_interaction_sizes: [32, 32, 64, 64]
pyramid_interaction_edges: [20, 10, 5, 5]
pyramid_interaction_iterations: [6, 6, 6, 6]
pyramid_hierarchical_edges: 2
nb_node_layer: 3
nb_edge_layer: 2
output_layers: 3
nb_mlp_layer: 8
knn: 100
train_r: 1.0
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 500
lr: 0.002
factor: 0.97
share_weight: False
patience: 1
regime: []
max_epochs: 100
majority_cut: 0.5
log_weight_ratio: 0
bipartitegraph_sparsity: 3
supergraph_sparsity: 2
min_cluster_size: 3
min_samples: 3
DBSCAN_eps: 100
kmeans: 3000
clustering_model: HDBSCAN
assignmnet_loss_weight: 1.0
use_one_loss: False
update_nodes: False


# Toy Model
use_toy: False
num_tracks: 200
track_dis_width: 10
num_layers: 10
min_r: 1
max_r: 5
detector_width: 2
toy_eff: 0.9
toy_pur: 0.5