# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/usr/ryanliu/TrackML_data/filter_processed/

# Dataset parameters
datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [2000, 100, 100] # Number of [training, validation, testing] examples
true_edges: pid_true_edges
ptcut: 1.0
n_hits: 5
weight_leak: 1.0
weight_min: 0.5
pt_interval: 0.5
checkpointing: True
primary: False
noise: True
hard_ptcut: 0
edge_dropping_ratio: 0.
score_cut: 0.7

# Model parameters
model: EC-IN
spatial_channels: 3
cell_channels: 8
latent: 128
hidden: ratio
hidden_ratio: 2
emb_dim: 8
n_pure_interaction_graph_iters: 14
nb_node_layer: 3
nb_edge_layer: 2
output_layers: 3
knn: 100
train_r: 1.0
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 100
lr: 0.001
factor: 0.99
share_weight: False
patience: 1
regime: []
max_epochs: 300
majority_cut: 0.5
log_weight_ratio: 0


# Toy Model
use_toy: False
num_tracks: 200
track_dis_width: 10
num_layers: 10
min_r: 1
max_r: 5
detector_width: 2
toy_eff: 0.9
toy_pur: 0.5