# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_barrel_v2

# Dataset parameters
train_split: [1000, 10, 1000] # Number of [training, validation, testing] examples
signal_pt_interval: 500.
signal_pt_cut: 1000.
weight_leak: 0.0
weight_min: 0.0

# Model parameters
spatial_channels: 3
emb_dim: 16
max_eff: 0.98
hidden: 1024
cell_channels: 8
nb_layer: 6
weight_ratio: 0.3
r_train: 1.0
r_val: 1.0
r_test: 1.0
use_bidir_truth: False
use_geodesic_distance: True
use_dual_encoder: True
knn: 100
warmup: 1000
margin: 1.0
margin_buffer: 1.5
lr: 0.0001
factor: 0.3
patience: 15
regime: [ci]
max_epochs: 50
max_steps: 10000

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/homes/r/ryanliu/ExaTrkX/wandb_data
