# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel_v3

# Dataset parameters

datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [1000, 10, 0] # Number of [training, validation, testing] examples
ptcut: 1000.
n_hits: 3
primary: True
cheat: False
truth_key: y
score_cut: 0.5

# Model parameters
max_eff: 0.95
global_information: False
spatial_channels: 3
cell_channels: 8
latent: 128
hidden: 128
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
output_layers: 3
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 500
lr: 0.0005
factor: 0.97
patience: 1
regime: []
max_epochs: 100
share_weight: False
weight_ratio: 1