# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel_v3

# Dataset parameters

datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [1000, 10, 0] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
score_cut: 0.15
random_edges: 0.1
n_hits: 3
primary: True

# Model parameters
max_eff: 0.9
emb_dim: 1
knn_r: 1.
spatial_channels: 3
cell_channels: 8
hidden: 256
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
output_layers: 2
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 500
lr: 0.0005
factor: 0.3
patience: 10
margin: 1
regime: [ci]
weights: [1.,1.,1.] #true attractive, false attractive, true repulsive
embedding_regime: node
max_epochs: 20