# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/gnn_processed/0GeV_barrel_v3

# Dataset parameters

datatype_names: [train, val, test] # Which directory prefixes to use, assuming at least a train dataset 
train_split: [1000, 20, 0] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
score_cut: 0.15
ptcut: 1000.
n_hits: 3
primary: True
weight_leak: 0.00
weight_min: 0.
pt_interval: 500.
checkpointing: False

# Model parameters
spatial_channels: 3
cell_channels: 8
latent: 128
hidden: 256
clusters: 1200
n_interaction_graph_iters: 4
n_hierarchical_graph_iters: 6
nb_node_layer: 3
nb_edge_layer: 3
hidden_output_activation: Tanh
layernorm: True
hidden_activation: GELU
warmup: 500
lr: 0.001
factor: 0.99
share_weight: False
patience: 1
regime: []
max_epochs: 1000
majority_cut: 0.5
initialization_method: nn
att_on_supergraph: True
# Toy Model
use_toy: True
num_tracks: 100
num_layers: 10
min_r: 1
max_r: 5
detector_width: 2
toy_eff: 0.95
toy_pur: 0.5