# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_v2
project: ITk_1GeV

# Dataset parameters
pt_signal_min: 500.
pt_background_min: 500.
n_hits: 3.
primary_only: True
train_split: [1000, 20, 10] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
noise: False

# Model parameters
spatial_channels: 3
cell_channels: 8
emb_hidden: 1024
n_spaces: 1
nb_shared_layer: 6
nb_independent_layer: 1
emb_dim: 8
weight: 10
randomisation: 1
points_per_batch: 100000
r_train: 1.0
r_val: [1.0]
r_test: 1.5
knn: 60
warmup: 1000
margin: 0.5
lr: 0.0005
factor: 0.3
patience: 15
regime: [rp, ci, hnm]
max_epochs: 5

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/homes/r/ryanliu/ExaTrkX/wandb_data
