# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_v2
project: ITk_1GeV

# Dataset parameters
train_split: [5000, 10, 4000] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
normalize: True
signal_pt_scale: 0.
val_on_noise: True

# Model parameters
spatial_channels: 3
emb_dim: 8
emb_hidden: 1024
cell_channels: 8
n_spaces: 1
nb_shared_layer: 5
nb_independent_layer: 2
weight: 10
randomisation: 2
signal_points_per_batch: 100000
r_train: 1.0
r_val: 1.0
r_test: 1.5
knn: 60
warmup: 1000
margin: 1.0
lr: 0.0002
factor: 0.3
patience: 10
regime: [rp, ci, hnm]
max_epochs: 10
max_steps: 10000

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/homes/r/ryanliu/ExaTrkX/wandb_data
