# Input/output configuration
input_dir: /global/cfs/cdirs/m3443/data/ITk-upgrade/processed/feature_store/feature_store_modulewise_barrel_v2
project: ITk_1GeV

# Dataset parameters
train_split: [1000, 10, 4000] # Number of [training, validation, testing] examples
true_edges: modulewise_true_edges
normalize: True
signal_pt_interval: 500.
signal_pt_cut: 1000.
val_on_noise: True
punish_same_pid: False
weight_leak: 0.0001

# Model parameters
spatial_channels: 3
emb_dim: 16
max_eff: 0.98
emb_hidden: 1024
cell_channels: 8
n_spaces: 1
nb_shared_layer: 5
nb_independent_layer: 2
weight_ratio: 4
signal_points_per_batch: 100000
randomisation: 2
r_train: 0.5
r_val: 1.0
r_test: 1.5
knn: 60 # actual value will be knn/(n_space + 1)
warmup: 1000
margin: 1.0
lr: 0.0005
factor: 0.3
patience: 3
regime: [rp, ci, hnm]
max_epochs: 10
max_steps: 10000
square: True

# Postprocessing
callbacks: EmbeddingTelemetry #[EmbeddingInferenceCallback, 

# Logging
wandb_save_dir: /global/homes/r/ryanliu/ExaTrkX/wandb_data
